repos:
  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        entry: bash -c 'pip-audit -r src/requirements.txt'
        language: system
        files: src/requirements.txt
        pass_filenames: false