repos:
  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        entry: pip-audit
        language: system
        args: ["-r", "requirements.txt"]
        files: requirements.txt
        pass_filenames: false